### ISSUE TITLE
Glossar in PDF

### ISSUE THREAD

**Issue by Weitspringer** [bendixsonnenberg/CS-Select-Allg#6]
Glossar wird in PDF nicht geprintet.

**Comment by bendixsonnenberg** [comment]
man muss einmal `makeglossaries` ausfphren nach `pdflatex`, dann nochmal `pdflatex`
zumindist unter linux ist das so, im IDE kann ich nicht helfen

**Comment by Santaaa348** [comment]
http://www.math.ucsd.edu/~jeggers/latex/glossariesbegin.pdf
Seite 10 - 11 haben mir geholfen :D Irgendwie muss man da was extra machen..
